
name: nginx

services:
  nginx-server:
    container_name: nginx
    image: nginx-image:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ${NGINX_PATH}/config:/config
      - ${NGINX_PATH}/data:/data
    env_file:
      - .env
    ports:
      - '80:80'
    hostname: nginx
    networks:
      local_network: {}
    restart: unless-stopped  
      
networks:
  local_network:
    external: true