
name: freeswitch

services:
  freeswitch-server:
    container_name: freeswitch
    image: freeswitch-image
    environment:
      - TZ=${TZ}
      - EXTERNAL_IP=${MACVLAN_ADDR}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DATA_PATH}:/data
    env_file:
      - .env
    ports:
      - '2222:22'
      - '5060:5060/tcp'
      - '5060:5060/udp'
      - '5080:5080/tcp'
      - '5080:5080/udp'
      - '8021:8021/tcp'
    hostname: freeswitch
    restart: unless-stopped
    networks:
      macvlan_network:
        ipv4_address: ${MACVLAN_ADDR}
    
networks:
  macvlan_network:
    external: true